main: com.corydio.App
name: corporations
version: 1.0
description: Player corporations
api-version: 1.19
authors: [cory]

commands:
  corpcreate:
    description: Create a new corporation
    usage: /corpcreate <name>
    permission: corporations.corp.create

  bank:
    description: Open corporation bank
    usage: Open the bank for your corporation. Must be in a corporation to use.
    permission: corporations.bank